/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgriTrust {
      
    export type FarmerStruct = {id: string, name: string, location: string, province: string, district: string, ward: string, village: string, status: BigNumberish, registeredBy: AddressLike, exists: boolean, registeredAt: BigNumberish, reviewedAt: BigNumberish, eligibleDate: BigNumberish, hasCollected: boolean, collectedAt: BigNumberish}

    export type FarmerStructOutput = [id: string, name: string, location: string, province: string, district: string, ward: string, village: string, status: bigint, registeredBy: string, exists: boolean, registeredAt: bigint, reviewedAt: bigint, eligibleDate: bigint, hasCollected: boolean, collectedAt: bigint] & {id: string, name: string, location: string, province: string, district: string, ward: string, village: string, status: bigint, registeredBy: string, exists: boolean, registeredAt: bigint, reviewedAt: bigint, eligibleDate: bigint, hasCollected: boolean, collectedAt: bigint }
  
    }

  export interface AgriTrustInterface extends Interface {
    getFunction(nameOrSignature: "activateOfficer" | "allocateFertilizer" | "applyAllocationPolicy" | "confirmDistribution" | "createOfficer(address,string)" | "createOfficer(address,string,string,string,string)" | "createSchedule" | "deactivateOfficer" | "eligibilityDelay" | "getAllFarmers" | "getAllocation" | "getAllocationPolicy" | "getAuditCount" | "getAuditEntry" | "getDistribution" | "getDistributionDetails" | "getFarmer" | "getFarmerCount" | "getFarmerDetails" | "getFarmerIdAt" | "getOfficer" | "getOfficerCount" | "getOfficerDetails" | "getOfficerWalletAt" | "isFarmerVerified" | "isOfficerActive" | "owner" | "registerFarmer" | "registerFarmerWithVillage" | "rejectFarmer" | "scheduleCount" | "schedules" | "setEligibilityDelay" | "verifyFarmer"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AllocationPolicyApplied" | "DistributionConfirmed" | "EligibilityDelayUpdated" | "FarmerRegistered" | "FarmerRejected" | "FarmerVerified" | "FertilizerAllocated" | "OfficerActivated" | "OfficerCreated" | "OfficerDeactivated" | "ScheduleCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'activateOfficer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'allocateFertilizer', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'applyAllocationPolicy', values: [string, string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmDistribution', values: [string]): string;
encodeFunctionData(functionFragment: 'createOfficer(address,string)', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'createOfficer(address,string,string,string,string)', values: [AddressLike, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'createSchedule', values: [string, string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deactivateOfficer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'eligibilityDelay', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllFarmers', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllocation', values: [string]): string;
encodeFunctionData(functionFragment: 'getAllocationPolicy', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'getAuditCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAuditEntry', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDistribution', values: [string]): string;
encodeFunctionData(functionFragment: 'getDistributionDetails', values: [string]): string;
encodeFunctionData(functionFragment: 'getFarmer', values: [string]): string;
encodeFunctionData(functionFragment: 'getFarmerCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getFarmerDetails', values: [string]): string;
encodeFunctionData(functionFragment: 'getFarmerIdAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOfficer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getOfficerCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOfficerDetails', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getOfficerWalletAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isFarmerVerified', values: [string]): string;
encodeFunctionData(functionFragment: 'isOfficerActive', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerFarmer', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'registerFarmerWithVillage', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'rejectFarmer', values: [string]): string;
encodeFunctionData(functionFragment: 'scheduleCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'schedules', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setEligibilityDelay', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifyFarmer', values: [string]): string;

    decodeFunctionResult(functionFragment: 'activateOfficer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allocateFertilizer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'applyAllocationPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmDistribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createOfficer(address,string)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createOfficer(address,string,string,string,string)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createSchedule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivateOfficer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eligibilityDelay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllFarmers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllocation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllocationPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuditCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuditEntry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDistribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDistributionDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmerCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmerDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFarmerIdAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOfficer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOfficerCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOfficerDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOfficerWalletAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isFarmerVerified', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOfficerActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerFarmerWithVillage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'scheduleCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'schedules', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEligibilityDelay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyFarmer', data: BytesLike): Result;
  }

  
    export namespace AllocationPolicyAppliedEvent {
      export type InputTuple = [timestamp: BigNumberish, wallet: AddressLike, province: string, district: string, ward: string, bagsPerFarmer: BigNumberish];
      export type OutputTuple = [timestamp: bigint, wallet: string, province: string, district: string, ward: string, bagsPerFarmer: bigint];
      export interface OutputObject {timestamp: bigint, wallet: string, province: string, district: string, ward: string, bagsPerFarmer: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DistributionConfirmedEvent {
      export type InputTuple = [timestamp: BigNumberish, wallet: AddressLike, farmerId: string];
      export type OutputTuple = [timestamp: bigint, wallet: string, farmerId: string];
      export interface OutputObject {timestamp: bigint, wallet: string, farmerId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EligibilityDelayUpdatedEvent {
      export type InputTuple = [timestamp: BigNumberish, delay: BigNumberish];
      export type OutputTuple = [timestamp: bigint, delay: bigint];
      export interface OutputObject {timestamp: bigint, delay: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FarmerRegisteredEvent {
      export type InputTuple = [timestamp: BigNumberish, wallet: AddressLike, farmerId: string, name: string, location: string];
      export type OutputTuple = [timestamp: bigint, wallet: string, farmerId: string, name: string, location: string];
      export interface OutputObject {timestamp: bigint, wallet: string, farmerId: string, name: string, location: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FarmerRejectedEvent {
      export type InputTuple = [timestamp: BigNumberish, wallet: AddressLike, farmerId: string];
      export type OutputTuple = [timestamp: bigint, wallet: string, farmerId: string];
      export interface OutputObject {timestamp: bigint, wallet: string, farmerId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FarmerVerifiedEvent {
      export type InputTuple = [timestamp: BigNumberish, wallet: AddressLike, farmerId: string];
      export type OutputTuple = [timestamp: bigint, wallet: string, farmerId: string];
      export interface OutputObject {timestamp: bigint, wallet: string, farmerId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FertilizerAllocatedEvent {
      export type InputTuple = [timestamp: BigNumberish, wallet: AddressLike, farmerId: string, quantity: BigNumberish];
      export type OutputTuple = [timestamp: bigint, wallet: string, farmerId: string, quantity: bigint];
      export interface OutputObject {timestamp: bigint, wallet: string, farmerId: string, quantity: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OfficerActivatedEvent {
      export type InputTuple = [timestamp: BigNumberish, wallet: AddressLike, farmerId: string];
      export type OutputTuple = [timestamp: bigint, wallet: string, farmerId: string];
      export interface OutputObject {timestamp: bigint, wallet: string, farmerId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OfficerCreatedEvent {
      export type InputTuple = [timestamp: BigNumberish, wallet: AddressLike, farmerId: string, name: string];
      export type OutputTuple = [timestamp: bigint, wallet: string, farmerId: string, name: string];
      export interface OutputObject {timestamp: bigint, wallet: string, farmerId: string, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OfficerDeactivatedEvent {
      export type InputTuple = [timestamp: BigNumberish, wallet: AddressLike, farmerId: string];
      export type OutputTuple = [timestamp: bigint, wallet: string, farmerId: string];
      export interface OutputObject {timestamp: bigint, wallet: string, farmerId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScheduleCreatedEvent {
      export type InputTuple = [timestamp: BigNumberish, scheduleId: BigNumberish, province: string, district: string, ward: string, bagsPerFarmer: BigNumberish, startTime: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [timestamp: bigint, scheduleId: bigint, province: string, district: string, ward: string, bagsPerFarmer: bigint, startTime: bigint, endTime: bigint];
      export interface OutputObject {timestamp: bigint, scheduleId: bigint, province: string, district: string, ward: string, bagsPerFarmer: bigint, startTime: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgriTrust extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgriTrust;
    waitForDeployment(): Promise<this>;

    interface: AgriTrustInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activateOfficer: TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    allocateFertilizer: TypedContractMethod<
      [farmerId: string, quantity: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    applyAllocationPolicy: TypedContractMethod<
      [province: string, district: string, ward: string, bagsPerFarmer: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmDistribution: TypedContractMethod<
      [farmerId: string, ],
      [void],
      'nonpayable'
    >
    

    
    "createOfficer(address,string)": TypedContractMethod<
      [wallet: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >
    

    
    "createOfficer(address,string,string,string,string)": TypedContractMethod<
      [wallet: AddressLike, name: string, province: string, district: string, ward: string, ],
      [void],
      'nonpayable'
    >
    

    
    createSchedule: TypedContractMethod<
      [province: string, district: string, ward: string, bagsPerFarmer: BigNumberish, durationDays: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deactivateOfficer: TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    eligibilityDelay: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAllFarmers: TypedContractMethod<
      [],
      [AgriTrust.FarmerStructOutput[]],
      'view'
    >
    

    
    getAllocation: TypedContractMethod<
      [farmerId: string, ],
      [[string, bigint, string, boolean, bigint]],
      'view'
    >
    

    
    getAllocationPolicy: TypedContractMethod<
      [province: string, district: string, ward: string, ],
      [[string, string, string, bigint, string, boolean, bigint]],
      'view'
    >
    

    
    getAuditCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getAuditEntry: TypedContractMethod<
      [index: BigNumberish, ],
      [[string, string, string, bigint]],
      'view'
    >
    

    
    getDistribution: TypedContractMethod<
      [farmerId: string, ],
      [[string, boolean, string, bigint]],
      'view'
    >
    

    
    getDistributionDetails: TypedContractMethod<
      [farmerId: string, ],
      [[string, boolean, string, bigint, bigint]],
      'view'
    >
    

    
    getFarmer: TypedContractMethod<
      [farmerId: string, ],
      [[string, string, string, bigint, string, boolean, bigint, bigint]],
      'view'
    >
    

    
    getFarmerCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getFarmerDetails: TypedContractMethod<
      [farmerId: string, ],
      [[string, string, string, string, string, string, string, bigint, string, boolean, bigint, bigint, bigint, boolean, bigint]],
      'view'
    >
    

    
    getFarmerIdAt: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getOfficer: TypedContractMethod<
      [wallet: AddressLike, ],
      [[string, string, boolean, boolean, bigint, bigint]],
      'view'
    >
    

    
    getOfficerCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getOfficerDetails: TypedContractMethod<
      [wallet: AddressLike, ],
      [[string, string, string, string, string, boolean, boolean, bigint, bigint]],
      'view'
    >
    

    
    getOfficerWalletAt: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    isFarmerVerified: TypedContractMethod<
      [farmerId: string, ],
      [boolean],
      'view'
    >
    

    
    isOfficerActive: TypedContractMethod<
      [wallet: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerFarmer: TypedContractMethod<
      [farmerId: string, name: string, locationOrVillage: string, ],
      [void],
      'nonpayable'
    >
    

    
    registerFarmerWithVillage: TypedContractMethod<
      [farmerId: string, name: string, village: string, ],
      [void],
      'nonpayable'
    >
    

    
    rejectFarmer: TypedContractMethod<
      [farmerId: string, ],
      [void],
      'nonpayable'
    >
    

    
    scheduleCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    schedules: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, boolean] & {id: bigint, province: string, district: string, ward: string, bagsPerFarmer: bigint, startTime: bigint, endTime: bigint, isActive: boolean }],
      'view'
    >
    

    
    setEligibilityDelay: TypedContractMethod<
      [delay: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    verifyFarmer: TypedContractMethod<
      [farmerId: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activateOfficer'): TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allocateFertilizer'): TypedContractMethod<
      [farmerId: string, quantity: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'applyAllocationPolicy'): TypedContractMethod<
      [province: string, district: string, ward: string, bagsPerFarmer: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmDistribution'): TypedContractMethod<
      [farmerId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createOfficer(address,string)'): TypedContractMethod<
      [wallet: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createOfficer(address,string,string,string,string)'): TypedContractMethod<
      [wallet: AddressLike, name: string, province: string, district: string, ward: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createSchedule'): TypedContractMethod<
      [province: string, district: string, ward: string, bagsPerFarmer: BigNumberish, durationDays: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deactivateOfficer'): TypedContractMethod<
      [wallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'eligibilityDelay'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAllFarmers'): TypedContractMethod<
      [],
      [AgriTrust.FarmerStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllocation'): TypedContractMethod<
      [farmerId: string, ],
      [[string, bigint, string, boolean, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllocationPolicy'): TypedContractMethod<
      [province: string, district: string, ward: string, ],
      [[string, string, string, bigint, string, boolean, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getAuditCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getAuditEntry'): TypedContractMethod<
      [index: BigNumberish, ],
      [[string, string, string, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getDistribution'): TypedContractMethod<
      [farmerId: string, ],
      [[string, boolean, string, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getDistributionDetails'): TypedContractMethod<
      [farmerId: string, ],
      [[string, boolean, string, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmer'): TypedContractMethod<
      [farmerId: string, ],
      [[string, string, string, bigint, string, boolean, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmerCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmerDetails'): TypedContractMethod<
      [farmerId: string, ],
      [[string, string, string, string, string, string, string, bigint, string, boolean, bigint, bigint, bigint, boolean, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getFarmerIdAt'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOfficer'): TypedContractMethod<
      [wallet: AddressLike, ],
      [[string, string, boolean, boolean, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getOfficerCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getOfficerDetails'): TypedContractMethod<
      [wallet: AddressLike, ],
      [[string, string, string, string, string, boolean, boolean, bigint, bigint]],
      'view'
    >;
getFunction(nameOrSignature: 'getOfficerWalletAt'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isFarmerVerified'): TypedContractMethod<
      [farmerId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isOfficerActive'): TypedContractMethod<
      [wallet: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerFarmer'): TypedContractMethod<
      [farmerId: string, name: string, locationOrVillage: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerFarmerWithVillage'): TypedContractMethod<
      [farmerId: string, name: string, village: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rejectFarmer'): TypedContractMethod<
      [farmerId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'scheduleCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'schedules'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, boolean] & {id: bigint, province: string, district: string, ward: string, bagsPerFarmer: bigint, startTime: bigint, endTime: bigint, isActive: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'setEligibilityDelay'): TypedContractMethod<
      [delay: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyFarmer'): TypedContractMethod<
      [farmerId: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AllocationPolicyApplied'): TypedContractEvent<AllocationPolicyAppliedEvent.InputTuple, AllocationPolicyAppliedEvent.OutputTuple, AllocationPolicyAppliedEvent.OutputObject>;
getEvent(key: 'DistributionConfirmed'): TypedContractEvent<DistributionConfirmedEvent.InputTuple, DistributionConfirmedEvent.OutputTuple, DistributionConfirmedEvent.OutputObject>;
getEvent(key: 'EligibilityDelayUpdated'): TypedContractEvent<EligibilityDelayUpdatedEvent.InputTuple, EligibilityDelayUpdatedEvent.OutputTuple, EligibilityDelayUpdatedEvent.OutputObject>;
getEvent(key: 'FarmerRegistered'): TypedContractEvent<FarmerRegisteredEvent.InputTuple, FarmerRegisteredEvent.OutputTuple, FarmerRegisteredEvent.OutputObject>;
getEvent(key: 'FarmerRejected'): TypedContractEvent<FarmerRejectedEvent.InputTuple, FarmerRejectedEvent.OutputTuple, FarmerRejectedEvent.OutputObject>;
getEvent(key: 'FarmerVerified'): TypedContractEvent<FarmerVerifiedEvent.InputTuple, FarmerVerifiedEvent.OutputTuple, FarmerVerifiedEvent.OutputObject>;
getEvent(key: 'FertilizerAllocated'): TypedContractEvent<FertilizerAllocatedEvent.InputTuple, FertilizerAllocatedEvent.OutputTuple, FertilizerAllocatedEvent.OutputObject>;
getEvent(key: 'OfficerActivated'): TypedContractEvent<OfficerActivatedEvent.InputTuple, OfficerActivatedEvent.OutputTuple, OfficerActivatedEvent.OutputObject>;
getEvent(key: 'OfficerCreated'): TypedContractEvent<OfficerCreatedEvent.InputTuple, OfficerCreatedEvent.OutputTuple, OfficerCreatedEvent.OutputObject>;
getEvent(key: 'OfficerDeactivated'): TypedContractEvent<OfficerDeactivatedEvent.InputTuple, OfficerDeactivatedEvent.OutputTuple, OfficerDeactivatedEvent.OutputObject>;
getEvent(key: 'ScheduleCreated'): TypedContractEvent<ScheduleCreatedEvent.InputTuple, ScheduleCreatedEvent.OutputTuple, ScheduleCreatedEvent.OutputObject>;

    filters: {
      
      'AllocationPolicyApplied(uint256,address,string,string,string,uint256)': TypedContractEvent<AllocationPolicyAppliedEvent.InputTuple, AllocationPolicyAppliedEvent.OutputTuple, AllocationPolicyAppliedEvent.OutputObject>;
      AllocationPolicyApplied: TypedContractEvent<AllocationPolicyAppliedEvent.InputTuple, AllocationPolicyAppliedEvent.OutputTuple, AllocationPolicyAppliedEvent.OutputObject>;
    

      'DistributionConfirmed(uint256,address,string)': TypedContractEvent<DistributionConfirmedEvent.InputTuple, DistributionConfirmedEvent.OutputTuple, DistributionConfirmedEvent.OutputObject>;
      DistributionConfirmed: TypedContractEvent<DistributionConfirmedEvent.InputTuple, DistributionConfirmedEvent.OutputTuple, DistributionConfirmedEvent.OutputObject>;
    

      'EligibilityDelayUpdated(uint256,uint256)': TypedContractEvent<EligibilityDelayUpdatedEvent.InputTuple, EligibilityDelayUpdatedEvent.OutputTuple, EligibilityDelayUpdatedEvent.OutputObject>;
      EligibilityDelayUpdated: TypedContractEvent<EligibilityDelayUpdatedEvent.InputTuple, EligibilityDelayUpdatedEvent.OutputTuple, EligibilityDelayUpdatedEvent.OutputObject>;
    

      'FarmerRegistered(uint256,address,string,string,string)': TypedContractEvent<FarmerRegisteredEvent.InputTuple, FarmerRegisteredEvent.OutputTuple, FarmerRegisteredEvent.OutputObject>;
      FarmerRegistered: TypedContractEvent<FarmerRegisteredEvent.InputTuple, FarmerRegisteredEvent.OutputTuple, FarmerRegisteredEvent.OutputObject>;
    

      'FarmerRejected(uint256,address,string)': TypedContractEvent<FarmerRejectedEvent.InputTuple, FarmerRejectedEvent.OutputTuple, FarmerRejectedEvent.OutputObject>;
      FarmerRejected: TypedContractEvent<FarmerRejectedEvent.InputTuple, FarmerRejectedEvent.OutputTuple, FarmerRejectedEvent.OutputObject>;
    

      'FarmerVerified(uint256,address,string)': TypedContractEvent<FarmerVerifiedEvent.InputTuple, FarmerVerifiedEvent.OutputTuple, FarmerVerifiedEvent.OutputObject>;
      FarmerVerified: TypedContractEvent<FarmerVerifiedEvent.InputTuple, FarmerVerifiedEvent.OutputTuple, FarmerVerifiedEvent.OutputObject>;
    

      'FertilizerAllocated(uint256,address,string,uint256)': TypedContractEvent<FertilizerAllocatedEvent.InputTuple, FertilizerAllocatedEvent.OutputTuple, FertilizerAllocatedEvent.OutputObject>;
      FertilizerAllocated: TypedContractEvent<FertilizerAllocatedEvent.InputTuple, FertilizerAllocatedEvent.OutputTuple, FertilizerAllocatedEvent.OutputObject>;
    

      'OfficerActivated(uint256,address,string)': TypedContractEvent<OfficerActivatedEvent.InputTuple, OfficerActivatedEvent.OutputTuple, OfficerActivatedEvent.OutputObject>;
      OfficerActivated: TypedContractEvent<OfficerActivatedEvent.InputTuple, OfficerActivatedEvent.OutputTuple, OfficerActivatedEvent.OutputObject>;
    

      'OfficerCreated(uint256,address,string,string)': TypedContractEvent<OfficerCreatedEvent.InputTuple, OfficerCreatedEvent.OutputTuple, OfficerCreatedEvent.OutputObject>;
      OfficerCreated: TypedContractEvent<OfficerCreatedEvent.InputTuple, OfficerCreatedEvent.OutputTuple, OfficerCreatedEvent.OutputObject>;
    

      'OfficerDeactivated(uint256,address,string)': TypedContractEvent<OfficerDeactivatedEvent.InputTuple, OfficerDeactivatedEvent.OutputTuple, OfficerDeactivatedEvent.OutputObject>;
      OfficerDeactivated: TypedContractEvent<OfficerDeactivatedEvent.InputTuple, OfficerDeactivatedEvent.OutputTuple, OfficerDeactivatedEvent.OutputObject>;
    

      'ScheduleCreated(uint256,uint256,string,string,string,uint256,uint256,uint256)': TypedContractEvent<ScheduleCreatedEvent.InputTuple, ScheduleCreatedEvent.OutputTuple, ScheduleCreatedEvent.OutputObject>;
      ScheduleCreated: TypedContractEvent<ScheduleCreatedEvent.InputTuple, ScheduleCreatedEvent.OutputTuple, ScheduleCreatedEvent.OutputObject>;
    
    };
  }