export const CENTRAL_PROVINCE_TREE = {
  Chibombo: {
    Katuba: ["Katuba"],
    Chilochabalenje: ["Chilochabalenje"],
    Cholokelo: ["Cholokelo"],
    Chunga: ["Chunga"],
    Kabile: ["Kabile"],
    Kamaila: ["Kamaila"],
    Muchenje: ["Muchenje"],
    Mungule: ["Mungule"],
    Keembe: ["Keembe"],
    Chaloshi: ["Chaloshi"],
    Chibombo: ["Chibombo"],
    Chikobo: ["Chikobo"],
    Chitanda: ["Chitanda"],
    Ipongo: ["Ipongo"],
    Itumbwe: ["Itumbwe"],
    Kakoma: ["Kakoma"],
    Kalola: ["Kalola"],
    Lunjofwa: ["Lunjofwa"],
    Malambanyama: ["Malambanyama"],
    Mashikili: ["Mashikili"],
    Muundu: ["Muundu"],
  },
  Chisamba: {
    Chisamba: ["Chisamba"],
    Chamuka: ["Chamuka"],
    Chikonkomene: ["Chikonkomene"],
    Kamano: ["Kamano"],
    Liteta: ["Liteta"],
    Miswa: ["Miswa"],
    Monangombe: ["Monangombe"],
    Mulungushi: ["Mulungushi"],
    Muswishi: ["Muswishi"],
    Mutenga: ["Mutenga"],
    Mwantaya: ["Mwantaya"],
    Mwapula: ["Mwapula"],
  },
  Chitambo: {
    Chitambo: ["Chitambo"],
    Chalilo: ["Chalilo"],
    Chipundu: ["Chipundu"],
    Kabansa: ["Kabansa"],
    Kanona: ["Kanona"],
    Katonga: ["Katonga"],
    Lulimala: ["Lulimala"],
    Luombwa: ["Luombwa"],
    Lusenga: ["Lusenga"],
    Lushibashi: ["Lushibashi"],
    Mailo: ["Mailo"],
    Muchinka: ["Muchinka"],
    Mweshe: ["Mweshe"],
    Nakatambo: ["Nakatambo"],
    Serenje: ["Serenje"],
  },
  Kabwe: {
    Mukobeko: ["Mine", "Highridge"],
    Bwacha: ["Bwacha"],
    "Ben Kafupi": ["Ben Kafupi"],
    Chililalila: ["Chililalila"],
    Chimanimani: ["Chimanimani"],
    Chinyanja: ["Chinyanja"],
    "Kang'omba": ["Kang'omba"],
    Kawama: ["Kawama"],
    Makululu: ["Makululu"],
    Munga: ["Munga"],
    Munyama: ["Munyama"],
    "Muwowo East": ["Muwowo East"],
    "Muwowo West": ["Muwowo West"],
    Ngungu: ["Ngungu"],
    Zambezi: ["Zambezi"],
    "Kabwe Central": ["Kabwe Central"],
    Chirwa: ["Chirwa"],
    "David Ramushu": ["David Ramushu"],
    Highridge: ["Highridge"],
    "Justine Kabwe": ["Justine Kabwe"],
    Kalonga: ["Kalonga"],
    Kaputula: ["Kaputula"],
    Katondo: ["Katondo"],
    Luangwa: ["Luangwa"],
    Luansase: ["Luansase"],
    Lukanga: ["Lukanga"],
    Moomba: ["Moomba"],
    Mpima: ["Mpima"],
    Nakoli: ["Nakoli"],
    Njanji: ["Njanji"],
    Waya: ["Waya"],
  },
  "Kapiri Mposhi": {
    "Kapiri Mposhi": ["Kapiri Mposhi"],
    "Chang'ondo": ["Chang'ondo"],
    Chibwelelo: ["Chibwelelo"],
    Imansa: ["Imansa"],
    Kabwale: ["Kabwale"],
    Kakwelesa: ["Kakwelesa"],
    Kampumba: ["Kampumba"],
    Kasanta: ["Kasanta"],
    Kashitu: ["Kashitu"],
    Lukanga: ["Lukanga"],
    Lunchu: ["Lunchu"],
    Lunsemfwa: ["Lunsemfwa"],
    Mpunde: ["Mpunde"],
    Mubofwe: ["Mubofwe"],
    Munga: ["Munga"],
    Mushimbili: ["Mushimbili"],
    Muteteshi: ["Muteteshi"],
    Nchembwe: ["Nchembwe"],
  },
  Luano: {
    "Mkushi South": ["Mkushi South"],
    Chimika: ["Chimika"],
    "Ching'ombe": ["Ching'ombe"],
    Chipaba: ["Chipaba"],
    Kamimbya: ["Kamimbya"],
    Katukutu: ["Katukutu"],
    Lundashi: ["Lundashi"],
    Lwambulu: ["Lwambulu"],
    Mibanga: ["Mibanga"],
    Munda: ["Munda"],
    Muswishi: ["Muswishi"],
    Mwalala: ["Mwalala"],
    Nkomashi: ["Nkomashi"],
  },
  Mkushi: {
    "Mkushi North": ["Mkushi North"],
    Chalata: ["Chalata"],
    Chibefwe: ["Chibefwe"],
    Chikanda: ["Chikanda"],
    Chitina: ["Chitina"],
    Kabengeleshi: ["Kabengeleshi"],
    Kalwa: ["Kalwa"],
    Matuku: ["Matuku"],
    Munsakamba: ["Munsakamba"],
    Munshibemba: ["Munshibemba"],
    Musofu: ["Musofu"],
    Nkolonga: ["Nkolonga"],
    Nkulumashiba: ["Nkulumashiba"],
    Nkumbi: ["Nkumbi"],
    Nshinso: ["Nshinso"],
    Tembwe: ["Tembwe"],
    "Upper Lunsemfwa": ["Upper Lunsemfwa"],
  },
  Mumbwa: {
    Mumbwa: ["Mumbwa"],
    Chibolyo: ["Chibolyo"],
    Kalwanyembe: ["Kalwanyembe"],
    Kamilambo: ["Kamilambo"],
    Lutale: ["Lutale"],
    Makebo: ["Makebo"],
    Mpusu: ["Mpusu"],
    Mumba: ["Mumba"],
    Mupona: ["Mupona"],
    Nalusanga: ["Nalusanga"],
    Naluvwi: ["Naluvwi"],
    Nambala: ["Nambala"],
    Shimbizhi: ["Shimbizhi"],
    Nangoma: ["Nangoma"],
    Chisalu: ["Chisalu"],
    Choma: ["Choma"],
    Matala: ["Matala"],
    Myooye: ["Myooye"],
    Nakasaka: ["Nakasaka"],
    Nalubanda: ["Nalubanda"],
    Shichanzu: ["Shichanzu"],
  },
  Ngabwe: {
    Lufubu: ["Lufubu"],
    Chilwa: ["Chilwa"],
    Chisanga: ["Chisanga"],
    Chisangwa: ["Chisangwa"],
    Chitumba: ["Chitumba"],
    Iwonde: ["Iwonde"],
    Luamala: ["Luamala"],
    Mukubwe: ["Mukubwe"],
    Ngabwe: ["Ngabwe"],
  },
  Serenje: {
    Muchinga: ["Muchinga"],
    Chibale: ["Chibale"],
    Chisomo: ["Chisomo"],
    "Kabwe Kupela": ["Kabwe Kupela"],
    Lukusashi: ["Lukusashi"],
    Masaninga: ["Masaninga"],
    Sancha: ["Sancha"],
    Serenje: ["Serenje"],
    Chisangwa: ["Chisangwa"],
    Ibolelo: ["Ibolelo"],
    Kabamba: ["Kabamba"],
    Kashishi: ["Kashishi"],
    Lupiya: ["Lupiya"],
    Mbaswa: ["Mbaswa"],
    Milenje: ["Milenje"],
    Muchinda: ["Muchinda"],
    Musangashi: ["Musangashi"],
  },
  Shibuyunji: {
    Mwembeshi: ["Mwembeshi"],
    Chabota: ["Chabota"],
    Chikonka: ["Chikonka"],
    Kalundu: ["Kalundu"],
    "Kapyanga East": ["Kapyanga East"],
    "Kapyanga West": ["Kapyanga West"],
    Makombwe: ["Makombwe"],
    Mukulaikwa: ["Mukulaikwa"],
    Mutombe: ["Mutombe"],
    Nakaiba: ["Nakaiba"],
    Nampeya: ["Nampeya"],
    Nampundwe: ["Nampundwe"],
    Sala: ["Sala"],
  },
};

export const LUSAKA_PROVINCE_TREE = {
  Chilanga: {
    Chilanga: ["Chilanga"],
    Chilongolo: ["Chilongolo"],
    Chinyanja: ["Chinyanja"],
    Kalundu: ["Kalundu"],
    Kasupe: ["Kasupe"],
    Mondengwa: ["Mondengwa"],
    "Mount Makulu": ["Mount Makulu"],
    Mwembeshi: ["Mwembeshi"],
    Nakachenje: ["Nakachenje"],
    Namalombwe: ["Namalombwe"],
    "New Farms": ["New Farms"],
    Nyemba: ["Nyemba"],
  },
  Chongwe: {
    Chongwe: ["Chongwe"],
    Chainda: ["Chainda"],
    Chalimbana: ["Chalimbana"],
    Chinkuli: ["Chinkuli"],
    Kanakantapa: ["Kanakantapa"],
    Kapete: ["Kapete"],
    Kapwayambale: ["Kapwayambale"],
    Kasenga: ["Kasenga"],
    Kasisi: ["Kasisi"],
    Katoba: ["Katoba"],
    Lwimba: ["Lwimba"],
    Madido: ["Madido"],
    Manyika: ["Manyika"],
    Mulenje: ["Mulenje"],
    Mwalumina: ["Mwalumina"],
    Nakatindi: ["Nakatindi"],
    Nchute: ["Nchute"],
    Ngwerere: ["Ngwerere"],
    Njolwe: ["Njolwe"],
    Ntandabale: ["Ntandabale"],
    Palabana: ["Palabana"],
  },
  Kafue: {
    Kafue: ["Kafue"],
    Chifwema: ["Chifwema"],
    Chikupi: ["Chikupi"],
    Chisakila: ["Chisakila"],
    Chisankane: ["Chisankane"],
    Chitende: ["Chitende"],
    Chiyaba: ["Chiyaba"],
    Kabweza: ["Kabweza"],
    Kambale: ["Kambale"],
    Kasenje: ["Kasenje"],
    Lukolongo: ["Lukolongo"],
    Magoba: ["Magoba"],
    Malundu: ["Malundu"],
    Matanda: ["Matanda"],
    Mungu: ["Mungu"],
    Shabusale: ["Shabusale"],
    Shikoswe: ["Shikoswe"],
    Shimabala: ["Shimabala"],
  },
  Luangwa: {
    Feira: ["Feira"],
    Chikoma: ["Chikoma"],
    Chiriwe: ["Chiriwe"],
    Dzalo: ["Dzalo"],
    Kabowo: ["Kabowo"],
    Kaluluzi: ["Kaluluzi"],
    Kapoche: ["Kapoche"],
    Katondwe: ["Katondwe"],
    Kaunga: ["Kaunga"],
    Kavuula: ["Kavuula"],
    Lunya: ["Lunya"],
    "M'kaliva": ["M'kaliva"],
    Mandombe: ["Mandombe"],
    Mankhokwe: ["Mankhokwe"],
    Mburuma: ["Mburuma"],
    Mphuka: ["Mphuka"],
    Mwalilia: ["Mwalilia"],
    Phwazi: ["Phwazi"],
  },
  Lusaka: {
    Kanyama: ["John Laing", "George"],
    Matero: ["Kabanana", "Chunga"],
    Chawama: ["Chawama"],
    "John Ho": ["John Ho"],
    Lilayi: ["Lilayi"],
    Nkoloma: ["Nkoloma"],
    Kabwata: ["Kabwata"],
    Chilenje: ["Chilenje"],
    Kamulanga: ["Kamulanga"],
    Kamwala: ["Kamwala"],
    Libala: ["Libala"],
    Chinika: ["Chinika"],
    "Garden Park": ["Garden Park"],
    "Harry Mwanga": ["Harry Mwanga"],
    Nkumbula: ["Nkumbula"],
    "Makeni Villa": ["Makeni Villa"],
    Munkolo: ["Munkolo"],
    "Lusaka Central": ["Lusaka Central"],
    Independence: ["Independence"],
    Kabulonga: ["Kabulonga"],
    Lubwa: ["Lubwa"],
    Silwizya: ["Silwizya"],
    Mandevu: ["Mandevu"],
    Chaisa: ["Chaisa"],
    "Justin Kabwe": ["Justin Kabwe"],
    Mpulungu: ["Mpulungu"],
    Mulungushi: ["Mulungushi"],
    Ngwerere: ["Ngwerere"],
    "Raphael Chota": ["Raphael Chota"],
    Roma: ["Roma"],
    Kapwepwe: ["Kapwepwe"],
    Lima: ["Lima"],
    Muchinga: ["Muchinga"],
    Mwembeshi: ["Mwembeshi"],
    Munali: ["Munali"],
    Chainda: ["Chainda"],
    Chakunkula: ["Chakunkula"],
    Kalikiliki: ["Kalikiliki"],
    Kalingalinga: ["Kalingalinga"],
    Mtendere: ["Mtendere"],
  },
  Rufunsa: {
    Rufunsa: ["Rufunsa"],
    Bunda_bunda: ["Bunda_bunda"],
    Chamulimba: ["Chamulimba"],
    Chintimbwi: ["Chintimbwi"],
    Kabuyu: ["Kabuyu"],
    Kankumba: ["Kankumba"],
    Mankhanda: ["Mankhanda"],
    Mulamba: ["Mulamba"],
    Mwachilele: ["Mwachilele"],
    Nyamanongo: ["Nyamanongo"],
    Nyangwena: ["Nyangwena"],
    Shikabeta: ["Shikabeta"],
  },
};

export const LOCATION_TREE_SEEDED = {
  Lusaka: LUSAKA_PROVINCE_TREE,
  Central: {
    Kabwe: CENTRAL_PROVINCE_TREE.Kabwe,
  },
};

export default LOCATION_TREE_SEEDED;
